hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "a2bbcf538477125e1241c5f617fa1b72d0d8d88f48b893fe6c1557829dfe7c92"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "a66627dcb9b7d145f2c7da43d6cd43797f8ed907c1d122755170a09eded1953a"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "35058f2b4e05ff3b459d130620b8c4ee78275fb06ff96d5b6319fe8705ed3e68"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "cea82e078dd6c0ae66b98d63650b54f4d19a85e7df2bcc80f2061bb8cb94d899"
metafile = true

[[files]]
file = "mods/better-block-entities.pw.toml"
hash = "99c42c071d66832e23ba561bdb1cee08c02aa5b40996207c774968b370aed1be"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "f788af34726f13d08cf5ce59148cdc5dec712c478af921f925b4aa90838d2288"
metafile = true

[[files]]
file = "mods/capture-playback.pw.toml"
hash = "56d804cb1b2716b5f672b50d7df1087deb42eaefaa3dfc765c6fd5fea8e5a2b6"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "c5c0572c7dc7cefa32cad157a292b4ee1edb9aa7a309c1d7955c1527c5e5463b"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "c965f5dd99f1f8f2c3f4a10180a51fb26d743ee47dd01853edaa5c9e87084686"
metafile = true

[[files]]
file = "mods/chunk-debug.pw.toml"
hash = "8f1b887bc08b7f2ec7413b333cfdb60c87501e63e28c1e4e34aefd83920f400f"
metafile = true

[[files]]
file = "mods/clear-despawn-reworked.pw.toml"
hash = "fa815918bfabc29fef2a4c67b61c1b0a37885600f00117376fdf36c59bb10da4"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "1702d34dcdbcfa879f5a74cd0e92996a22817d38edcb4defaa85e58b9fe831ab"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a3911d6c567a41c7e26806cc7776ae40ff720ad330c1c279458282b3312b3737"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "e9fe757406e2cfc2bf6d35ae834db79235c3d2cb2f03780ee594b83d85a39f5e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d5d3e85e133f25d0876d8432a7f27a280297935414f306d5d79372e4cd0c47c1"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "9071b0f2487ec9054e68ac0a4d10aa0331b7fd60ab6015d958c7a58ad9ae44ec"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "eb37b22b8f6a353ff5c7da61eae5bf5cd41e1cc7613e30709e9e51fa1543b13c"
metafile = true

[[files]]
file = "mods/essentialaddons.pw.toml"
hash = "0304a4bfb402bc3f57eeb32898935ff17534f8488864f337c8a3e501466bbb3e"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
hash = "ba55d5ca216b440adb18c865cd6cde6439f485918adf32648c60e5c8df656ba5"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "4bc6473e188a4c14d5622af2b04cb021b6db7a8cb5f089c7daf0d114a5ee7f5e"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "cc4908287780a01a4b8f982712a94330f8368c00728766b5f615470be86db183"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "d6250f89ac5f0ac6ea08f1345d083c1fa5cbda12670ba016e1457ec6f6a8ce32"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "6839f53544009603fefc7f72b4f724bf1cbbe0d8d6c0a0f27bf53503655b5345"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "809b4169d72d4d004b30d18011e7ebc2037d1ed0d3ba15956d88c2ac914567d5"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "4bf2e24ca4d9783c2a3ef27e3cbf1003f02739058aaae4b3478a17e8a4de7f2c"
metafile = true

[[files]]
file = "mods/g4mespeed.pw.toml"
hash = "558891db3c6595025b4bc8d297e7daede207c9414fde78eb2fe394d34c74ff62"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4c6ab2508960668871df2b8b5fa6ad04641240eb83e150b11356f8ffebe8172c"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "c4b8bff059280b88e4472816f3e4834cf6a556d0cc111288adf9521a43785018"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "7b7999342af9d5555dc3851b23e9e45948fd6df25fea8113da4e680cb404383c"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "bd0464e85eca4256135312fd924744cdb5cb4a4590468d8f0463ecaa83d824a6"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "d52187679aae683d1db39eeda0725823b924ffe9d74623f10221a3d87bac2c95"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "38bf2b56bbd2cbb9cc4e3ac9e9ecdf415ff1152ff1bfd68d0843ed58d7a6ba02"
metafile = true

[[files]]
file = "mods/litematica-server-paster.pw.toml"
hash = "228efa737d9d07ea3f51120939d19737d42520a9852138444c695cf792f05beb"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "34f146223bfd30d15d53c48845af1b234a36d3fbf2283de0ac2c6a94911d538c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c17e2044dd7d4c03385a8889004b480af28ae7157d2cf414d4893d4d28fd40bd"
metafile = true

[[files]]
file = "mods/malibind.pw.toml"
hash = "d3cd39bfb3f8bdc30f60bfb4359931d85986ca7447d37c56ba59b0d620a1e175"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "aa634e462204115ca30e110459f8e6331cedc709fb0360870404c3e4eee0745b"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "756f377569d2d0aaba92942d9958f66e4b0d95f6c60e5d1aa2e0b7693bba10d5"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "4844eeacb69a87292556f478d3425e1d0255bbafef5b9f483d5652208313b449"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "03ad3937e8e3a60504ad259f6a4e0e51ba19effe7f2652935590e3498ffb72f1"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "b0c3306ae1f725135bcf54f708b307fec2b3d822f41c4bb867ba7d9742b4d2ff"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "9a71582e0488411b3c7d3c811cb3fe436ed0fb1a39e27451289137ad53c29c47"
metafile = true

[[files]]
file = "mods/nbt-copy.pw.toml"
hash = "61a88870e6bc360ce905178aa2c0cecd85d313df8087e394bfb985a26c7122dd"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "31188934bcb30e1c88efe708b3ffdb7b9ae34595815c909fceb244fbab31cb88"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "096dc6a2ca0d50b0958d0baa035e7c22f9e2cbe5dbeb7e14c108c4073d79de11"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "9e0266e282a6b5f52ea5208ba88cdf8ac71ac0d13b23f4f92b6e8ec15c1ecc16"
metafile = true

[[files]]
file = "mods/packed-packs.pw.toml"
hash = "718f55a6198d3633358803671ee688d02915cd039b9348cda48ec7023ac54d16"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "2433a43c0bff3e54a2e114c2430a235c54ed139ea72f5afbd3da267c6b92bc09"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "4f5091cce93e61ac3a4ec9e87e225f784f3f4469248eff58c16d5f7367cec5ee"
metafile = true

[[files]]
file = "mods/redstone-multimeter.pw.toml"
hash = "4e28cdd947e2fffa245a3654700a7ac4d5adb475260d4da1e4326950b3ef3eb4"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b00ac74cd5e95c34b8bd849c96323921629c1af0a6ef404b187d5f99a8aa88ac"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "f10b01f1c112138bd2cae598b8e5b3e8511b6c47155276002a8e4319c9b87a4e"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "f61627c24489f95e3458ecf3f74bdd5aac697e2bce1f62afeaa79f28a17e13c5"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "c981186152855877c0ad49d6d3e2fe0cc5ed8c7c86a009d31bcf9d2999f3e0ea"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "21e11cf309d0d27c88c4eb14874312d5ee2e6bbfc3742629733f54be3469fec5"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "cbe31523a511324897f507f664305b7696e5f682609f42a8c08effda13bdf889"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "215cc5c6ddfe21aa6e9c5b7f1d21af91cfef56563fb28b9f1e37cd2f7a745536"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "090c1ffa1815f260b19353ee892f4d519a489803c88f47bcebb66f5d6409e883"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "56985e39cf7dbc652cf65d1cf8e1a9c9008dcd2ff6f5cedd85ca53eb2f51e374"
metafile = true

[[files]]
file = "mods/techutils.pw.toml"
hash = "8c8419f94ff2ac7d44cf2ebc2dbf05558eb6b3268d99ce09ef32b3fcc32fa417"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "4bff6a40380cbe11c5a5ffb02b7eb69d528dc404d62d969023ba67684f99ef2c"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "217c6ce446626f2a4850b3ae27da49bcb42ae242c4bff0f31aa7fb7a62107195"
metafile = true

[[files]]
file = "mods/unobtainable-blocks.pw.toml"
hash = "e620c847af24c12c8fa9eeff26f2be1b8e5a5e027ff7140efd2d4f73ddc258b4"
metafile = true

[[files]]
file = "mods/viabackwards.pw.toml"
hash = "9b04f2984f485fa081ce181944e87dea3015cdfeb6b8813ff68823525d3b553f"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "695d8765874f311d578b9336753d9e4c9c2ce9df927a517614f234237fcd7e7a"
metafile = true

[[files]]
file = "mods/vkm.pw.toml"
hash = "7de9e06f6c35d09d84bcddd2ccbefd489cb88412661a84459308bc68109b27cc"
metafile = true

[[files]]
file = "mods/voxy.pw.toml"
hash = "5a32a818f9c756a56536b56298d1a95c81cf04fbf8f836db2655d4b3f3322d06"
metafile = true

[[files]]
file = "mods/wikirenderer.pw.toml"
hash = "4f1aa777033c2c634fe97f7d90561468e75bf5af47123d392939545267d1563b"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "8aea9229ab3b30b7c066b226de6b38585449467843aeb0cdc6a7f62d1a3dc1db"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "52e2529d56443d8efab4a753fdb935b0b08d775b9fdebaa42a7c8063d617dbe1"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "aaa154ce173239b75189aada35582b87cf2964706f2902d28a8fad305ebaa8cb"
metafile = true

[[files]]
file = "resourcepacks/redstone-tweaks.pw.toml"
hash = "31b53c71c2bf08da156167befe54b5717e71ee871e10ef78a70967a0bdc8b56b"
metafile = true
