hash-format = "sha256"

[[files]]
file = "mods/carpet.pw.toml"
hash = "fbb61854650a7cdf7eb2244e0599bae2f0541864a9b7cf74f8272972e6bdb18e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d53b229a5588d33a8dac8682cba4371b22b2cbe2541c7129506cfbd44daaf6f8"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "3acc4032bc86d6b65609f40c228006b06a273b02926d1cbc96acdfbb070f8e29"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "f4dd757c0e23aff8bda3ee7f9cca2faa2648ae5e9f9fefa8e27ec873cc05a50a"
metafile = true
