name = "RedstoneTools"
author = "Scorpio"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "635fb2e5da80592c5b935d95f3df52d79bf244f52e32716a7d46696d239d89ff"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
