hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "40d155c7c0c89697d3394c69cb629265625688977c9ec504df83b2a43af39e53"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "139f8141c2a17e3dc447958ca1b6593e39234e2067480e01c1b5660e481fa48b"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "13b46101e0b944b8445c4fd55f8a6e8f5a9b16ec43248191866758591a502b5f"
metafile = true

[[files]]
file = "mods/capture-playback.pw.toml"
hash = "15ed10cb68494e113f53245b1ebdc969f338103cc5a7b46023e5664d0aca1e21"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "d151ec8524017d975a2ee8b645019c0f520fa35cf9644e1c7b9cc180e04738a0"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "e91a3ba45e68981d557650956e7938d57d8fd42b9a2e15cd923941e8364a7f8c"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "ec036dd98526569c7848313f7fc9a840ae96766e425b71f8241432c23af222b9"
metafile = true

[[files]]
file = "mods/chunk-debug.pw.toml"
hash = "0d3011effeb92d3309bdbff8516ad4da943368cb9b81120e806c4cceffc18c2f"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "2fe34332ba38d3bc8ec72df3e75bf5a68ee271753ddcec9e9a6749d53aa1a7bb"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "95f4fa1d9efeb229245b6e2f99a74428d49426fdff1a611466dc72d3388e054f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b7e1ea2ef0d8772b56e160ae73880de0249fa0eb7c6d1aa6b3f53c8c92f9831c"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "a02f85709d84172e18a6a33fe431b855008d7879b207771f3e558e266202be8e"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "b5b31489c6bb8990f37b16ea74b85b7a532b2b7d2c29a2fa862b260e8e2e05a4"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "63b4ea3ddbc0808128812bf5d3013f87978c30aef346511348f452f3d1c75628"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
hash = "8f9115c5c13a044ea8038b1704d0b4905031a221516784a8b0de18d6858379e4"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "536f62406c34f76988f0bbb97d2233ebc5cd0e4472cfcdc04965a7b325435c70"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "a1095d36aa401ff208298a279c8b9faad51f041936164926012f20de0f3c3ff0"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "49313d469bceaa834b58226e2df59205fe48894e67854fad41d83cac2566ec99"
metafile = true

[[files]]
file = "mods/essentialaddons.pw.toml"
hash = "b3dc1525475a8b5fab2de56d76ec21d43c1ae7a07e2b0cd00af2a44ba5754244"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
hash = "b85cccb7a2813a7820832879db2b65640f4bee4ce29571658e101e5c4a7385f1"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "897d523fd4d02e925a8e0e2dbb1b951751d1e6e9ddd882aecebf00cabc80ee04"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "eff9bfe863883fb8fe7017f7a23b5622cb4e424540b4ada72e418c89a90bdc4f"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "5c6b552b876fbfbc49e8df3b6a6a30b8e701636823a960c556e4bb2fe00b9da9"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "767eea9287ca8b5f73fc9778d8fd653ebe8118bb8734c8b370bd255c262fd210"
metafile = true

[[files]]
file = "mods/g4mespeed.pw.toml"
hash = "a9704735662fc017243d420f97e7dc2cd8c02a24e8143a349de9592b0279f842"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "7a52fb440b4ff8e07ae649032ea0d167774d7730962fc4bed0e5ee435b6b575b"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "ef58702f000c2bce335ef4d300335eb3341f21cecd0d43b48bb26df822a4700d"
metafile = true

[[files]]
file = "mods/isometric-renders.pw.toml"
hash = "65776f5c5e25622a7149c5860098dee67587dfe7498124f38046485b7d1d19ff"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "0631b017a6220df50fda2b3bfa538842d8202c30770076c0c4d633519b02148d"
metafile = true

[[files]]
file = "mods/joacarpet.pw.toml"
hash = "3d94c3ff3af0602578ff671357f8a4a8c4c76906cb48a54e11ab09b7adfcff04"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "01f54d293d1008f22f8cfc9a43b4c8e5473d882c2ed7ca667cbcf55ae4d638bc"
metafile = true

[[files]]
file = "mods/litematica-server-paster.pw.toml"
hash = "68caf9f0630b07952421389dec3f4cb148f5422be804ef124dd9d050aabd6cac"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "609e5067280141ade05d8e0a8641ae1c2ac1f36ba26223acb29af0e677d5c833"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e1aea49ed8a6f2af853793ee649e69d27d872b080c4a4a30264a42022a4eabed"
metafile = true

[[files]]
file = "mods/magiclib.pw.toml"
hash = "6f3a01432d35575797350bfc75202977c46803d5bf6ea97880c72a63c48fd9d1"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "8b1f5ff6a14cbc21bc879bc773f0d0d592434b4eb7cc99a29f5b753a21ca16c4"
metafile = true

[[files]]
file = "mods/masa-gadget.pw.toml"
hash = "732794b595135d9ecdcc8aa896d4a1c50fb85762e11c07a132459967d25af0b2"
metafile = true

[[files]]
file = "mods/masaadditions.pw.toml"
hash = "93379cc0a6afd8ac69f03df0c79a515ea8b5b02bdd741401fcd9f967affb5c51"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "46c276d92968436f6dd9213c1283669c25a219fe00fbee2360c27630a1ba8a3f"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "682c345112a0296450041eb8529bcde162d4cc6fec0cc92621b21485bd29ac78"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "8d5b0c8263782eff65e1900eb9bb43d8f424a4212848593cca8fd3240368a7a9"
metafile = true

[[files]]
file = "mods/nbt-copy.pw.toml"
hash = "04cbef7e357aa7e104e9cc9b5b158244b88a7dd224ca65a6f526cbc2807a7d66"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "8dadf57f969d4fe86966696c8445c8fab4810d63389cea5a772f34e30e5f4876"
metafile = true

[[files]]
file = "mods/pick-block-pro.pw.toml"
hash = "a5ea067ea083e543404d093c59ed0f6999afcf7b9fb5d9df74c885a573c39549"
metafile = true

[[files]]
file = "mods/redstone-multimeter.pw.toml"
hash = "17100c46ab7c7c9bf702a3a41f0212c1b9b955875d078946ca06b6dd2832439a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "d347c75e741807b9b87b2df676149bc56efcf4338b4edaefc3509ade046884c9"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "1f91747b659019ecee0b99455f9120f00f0d98d40b48b5d43ccd0715c39db85e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "df7d2eba1d60778975ea3bfe42c119d62c04363805932f9f034734c4f03236b2"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "be4ac6a781ae128ccf641c3b37b75d943a61961186273d2ae66a0cc0435a2325"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "768c803d25c5fafebc2f39649b24c765b31ea5100d2c213da0486fc501fbb728"
metafile = true

[[files]]
file = "mods/subtick.pw.toml"
hash = "dda6dc2bd35775f1028bd9dd7adc409879192aa5e43a9dfaf6cf65b5369fe411"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "17d01d0f36779175cc24dd2061342d1da22afdfab93ec5ac3516ed4e3cb1287d"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "509dbb618e183549dc515dc8804cedce12ca2901fc68b34b99fd002651691eaa"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "43b039f35d2cf95a4d64466c2449a1f5986ca3d6c3e32d3a2d050c2dee5c00c5"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "d63beb4cff57822beeca29bdc8bfe1ded481d14146fdff27df57aa5417153e9f"
metafile = true

[[files]]
file = "mods/viabackwards.pw.toml"
hash = "9b04f2984f485fa081ce181944e87dea3015cdfeb6b8813ff68823525d3b553f"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "695d8765874f311d578b9336753d9e4c9c2ce9df927a517614f234237fcd7e7a"
metafile = true

[[files]]
file = "mods/viaversion.pw.toml"
hash = "c07cc2e99ff823f3c845d392e86aa5eff70fc36b19d350bc1fe5b0aa43b23db1"
metafile = true

[[files]]
file = "mods/vkm.pw.toml"
hash = "659ac83a1eeb27c2571e218aab66b02deb39ebb7c88352bfe39ebcc0fd1653af"
metafile = true

[[files]]
file = "mods/worldedit-hang-fix.pw.toml"
hash = "16c5dc2e8dbf22fbe5d8bdb25566b717201d1e9ea4067d9df957912900201c14"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "c33b045ee24809ab5e26dc1a42f364d5ca7cbf48c8d255e8f4021ed68dc1b08f"
metafile = true
