name = "RedstoneTools"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c45e45b786cbb53ea7ce08ba561259a2626a2f9a25ae7fe538a02bb813bcf1e"

[versions]
fabric = "0.18.4"
minecraft = "1.17.1"
