hash-format = "sha256"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "5639d3bbf68649553e0d68616b06be4d3839b1c1f5a4c99edb6ca846cbd4e7b4"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "a91b9fecfbd788861792429ca7c36c0492503b8000554cb87f89546bc884406a"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "64c5978784fe1f7418becc7cdbe2900d17af74583c0e2cbf5cf5d4b79d094cb5"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "91ebc6c38ea1c481b1f90108d3c6b57babf373b5cc4399c929617fbd21e7ccc6"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "fb605ec9729252c00fe598d1e6ecbbcbb94dd7021c2aa3378bcca3e6de49c002"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
hash = "27325c33e201926e28f1d6ecdd593d199f3a868531294c984818e7dc80fd3442"
metafile = true
