name = "RedstoneTools"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3faee55963b5ec498bcf861fa9ac1c3c841c1fa873e6c6cda0a41213ebe5526c"

[versions]
fabric = "0.18.4"
minecraft = "26.1-snapshot-6"

[options]
acceptable-game-versions = ["26.1-snapshot-4", "26.1-snapshot-5"]
