hash-format = "sha256"

[[files]]
file = "mods/auth-me.pw.toml"
hash = "83c4c221b72db7fe8b2c85e912ba669be9667f6a4e069b666f296e68a0979de6"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "f47380034dd3ef7fcf1d8645e8e5ce01dccfe5b66f5ef2580bcbf6a5f9e2f9a7"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "e4a56d984a7fef013586e1e1ebcfadf757234585745d9ea9580e1f603b4c04f1"
metafile = true

[[files]]
file = "mods/better-suggestions.pw.toml"
hash = "19a93243a5d2e31691fe161e700eda30a9a91aba1348a291bc8c7a5f5455c8db"
metafile = true

[[files]]
file = "mods/capture-playback.pw.toml"
hash = "aa6fb1adcd83002b294da850ec1fea45145d8d9544805b98dc7dcb880d66dbc4"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "fbc6a60b3d42c6a6fdcea82764e480049855e2ddc1b82d7edff448f6c12043be"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "7255a6b3a8d8eb0127f34a08867b46eb26494b43ef0b57192c9f28b9cdd779c3"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "16b4acea5f6398fc5baac567155aff0ee2d8da6b988a446f1c2f3a09f715a64d"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "ee353c9038fa9e8133d5dc52cae3b4d45649cba880fb4d0c5c0a2468b85db882"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1d3d810fb49f6b74078abfb8aa2816715cc2840ba6324c9fcabff984b9b72412"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "62336d6884fb9f08eb6245b4949580d8f8ca611148c35bdf0ac78714091658c9"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "cd4d0c2db8c45235322fb097de824765c2e9ef1a762f8870b08680b92b8cede0"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "721da889d74825f3f6e687c9de9795be1af4b99d3f3bd61858fbb3161cc24254"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
hash = "4ab83564a6e16a9b61b13b05e7f13d86ac05069a4b45b678eb0f3b6a66b460d0"
metafile = true

[[files]]
file = "mods/doormat.pw.toml"
hash = "36a31a3043a5f1391bcdaa81d0158983e5bf3073c2a068e871b4ead390e5bae1"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "9eadb937c438421e85a21338153114f97c75ab3dd6f3a49305bc8d0d7b3688aa"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "57290c27b39126c20e4e1654572902bc1b7fcff074572bd44507d9b4e28537b8"
metafile = true

[[files]]
file = "mods/essentialaddons.pw.toml"
hash = "cf600aea60f9e9d9c256c6cd16a9ae4299ca3f9d13060b16fea3d7106f1e5f3b"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
hash = "fe9b3bb23531114cb9093689d75a60863bdebe5192471ccf8b8303a5c91f2bdf"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "32ba5b383cc4307b7728d46ae92a5e0ba82c2cbf4924955c19824f2a2c79da8b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "8f244f59c21985af6fd86ee200b48108e795f291ee353317360f4cdb4b008b4f"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4387abb74dcfc93f9381c109fe76e7161ca7a91a1a642db4781b47f650c4ddab"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "d88352f607700aed0db6a0679d4a2a2eaba2a83d38696ca966c2dace0a32f2b7"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "86f3bf44d767d1b1a1e76e6db5bd99e757875daeb3f9a4ac2afef86d2b020151"
metafile = true

[[files]]
file = "mods/g4mespeed.pw.toml"
hash = "8596b9607008f84009bc689ae585852912ef3ac295165ae35a446cd070ddb86d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c3d4f2627461782145554911f6f5e79d91d25cb1cdfc2c7386769cf3b9c7b97f"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "515b020926d1fd0b6d1a32d106a376ba2c77bc5587bed99cecbc2d944ad18a99"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "aedaac031578bcfcf9cd635d88b778304e11f893864e4cbfbddb67a8c8e34c14"
metafile = true

[[files]]
file = "mods/isometric-renders.pw.toml"
hash = "024938a45ec95c469dd1b62cba496bbba6b4da2af452a34aa5236a87a2308d57"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "77e7a77f3406573090c9e81ebefc9a3e4b7ec3892b82376b77346d33b11bc713"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c7a27ddefc1a4b55d4e447902bbf6f43f797a69047dfc00278e16b1ff3e191c7"
metafile = true

[[files]]
file = "mods/litematica-server-paster.pw.toml"
hash = "b59431b7a3aef5d243cbce93a4671f1bf7f610ab06941fa9e8d4324ce8e73a60"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "0373144a94990dbb3f9c3e0006e3b5a787c51dda2b86a02e1fa61efed9772951"
metafile = true

[[files]]
file = "mods/litemoretica.pw.toml"
hash = "f81bf0d70d1ab483b194c6b1557e81d895d99072cee21d4302f6ce7efab1c9dc"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "8ee12811c34ff12dfbeb54851b33430ed624b3e06daead3a9bd57db6d8ff3878"
metafile = true

[[files]]
file = "mods/magiclib.pw.toml"
hash = "36bcfe2d871a008448c92eee1694802c21b793632fbfc3d60c095800ab297cf2"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "c1b191ca22d9b6f6ca8b1902f3f9fe8baaa06409b9526391292d8c10ff828099"
metafile = true

[[files]]
file = "mods/masa-gadget.pw.toml"
hash = "11fc5d57a574762a527e0b8ffe2ea4c1189d5e7fe0e786a9df8e7c2ec9630129"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "37d233dbdd7469d0235e1fe8ea8bb37a180600a9ed338341ceb87a7850085633"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "38ab12bf19d6cafd9208c4715a84cbfc1606af625f9fce9e253fed8251eaf506"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "06d0708b2f778731f7520021f2f3c2284a347fd6679f0227e97fea4140b374a8"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "a99f61741eea32a00fc2672c574eec79a292addc0ca6d84c138a4a079803389e"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7109df72174bc3fe15d9f5435767d63c69cb03b49910095618bd80888af08240"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "d7a57d91b5bc511f62f98ac586678d0ab2143864d86989de7992d03a729fc026"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "84cb0dcad9ac46d22adba4fb7924951affa6ac5e46027a3b25fa9a0db8d91b2b"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "46c39c1653c439e9ebda5f31a08d858336b3abcdcab4e1f926fcc75b10bd177b"
metafile = true

[[files]]
file = "mods/pick-block-pro.pw.toml"
hash = "ac9e6e3d1b470d7adf67a5231f2425e6e54c9ca2f2eaf5944993245d320e3422"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "fbdf5f9010d5f83277f4cdd30d33ced05fa1f7db2b3dad9cdaf114ee99f7d8db"
metafile = true

[[files]]
file = "mods/redstone-multimeter.pw.toml"
hash = "1a8be97bfe55eaf86038387356fa8d54c118a1ba3c2c34184baa8c1174de7c60"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "5cd85b655ab6f76b25205aa10ca5bc355b96f4e43d041a75907aa528f0dbd96f"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b61ab82e0128ac072934bc4f10a76d134e3f01c8ee1f41f5e8f1b7c1a2b59f1a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8db240d22fb9eb721449d55de72420a951edfca51d94090fa7db3d3a35c6002f"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "e4c2a01affdbc03498525292e879577ba28a563ed7a34691613a03e9772a9434"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "9a1695184cdb4646ae5deef3ed576e7dc1235cff1ff20493aa482a2c512928b0"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "7aeb9e2d53edb73844a4b2dda15757af35edfeac2d1137b0745a6d0f66989ba4"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "c35909b8aca011eccebb9bb2372800e790fd30d18fecaaed74148dc75eebbe69"
metafile = true

[[files]]
file = "mods/too-many-shortcuts.pw.toml"
hash = "41617ba34cbdf6a82bb287d9fc8960d1cd0bf080d1d4c36ed5c278057986baae"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "ee103bf45111c2cd7ea2d9b31087867dd4b0d07a4b7dad7b138a4ae506127b37"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "986ee5e7e26249a5b78912b39b718f856a91f13eaba66e12145b44afaaed1b49"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "d6922628df491a1da43a628366191cbceaaa32a44c833cf9cc48659485b992d1"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "37e9a032ef321ec3c361a8d53ae3e26b47680c65b74eb43c70f0ba4431320de8"
metafile = true

[[files]]
file = "mods/vkm.pw.toml"
hash = "628ee87e2086f7c2bdac867d30a1a0b129d97a4b0f69c0ffbc29e39174412117"
metafile = true

[[files]]
file = "mods/wecuifix.pw.toml"
hash = "f340cb4af842dc459304586183a6aa10d9c4464dd750dd564bb7cc6c3f403be9"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "0c35e0c34016643de8b6eb1add360eeabe81453470d1d8e58dbc8acbb32514f9"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "8242a7c369b2eab96c35806bf15b5e89c3132fd9fa704456efdb17aaa4f6f356"
metafile = true

[[files]]
file = "mods/yaca.pw.toml"
hash = "b93cfa3087cc6bb44363fc62837cfafdd1e621fe1e29c962435f66537cf1594e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "35e6474329bca40af9199e35d037a8accfa5ec0c6779ab06f912bd1f7a2bff0d"
metafile = true
