hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "076a83e9fbe5cb1ccf84756d9e2f762d87e3ae7f6ebc04e80083bfefc795430e"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "3dce25aadb32997de9e0591c6723b3b22e35402de42952c0c61b2629e697b24f"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "9cb3ff26393c643f491b0c135f607a7bd982433d8d08c19972132884797705c2"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "6c601c62688fc7105abb3cef4ca71cfed8411a62f2e809d99b4a101a021ee800"
metafile = true

[[files]]
file = "mods/better-suggestions.pw.toml"
hash = "5a804ce4fb5a8621512f24192a29a3ba96eace41a1bcf33be7ca1e646218d865"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "87fb001df1adc9839cb536396a5f26508f95e716524cac7895df869e2653ddf2"
metafile = true

[[files]]
file = "mods/capture-playback.pw.toml"
hash = "b0524ba0db087e1cb5465fcd3ee7218ec8a0258518ecf13216d63c1482d94d1a"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "0f50b5d341c09d8292f979c2355567679be26a8eef7f4ad2243234b518e5830a"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "a33c479fd9493dfe7d6513a64a69c8236d676fb82e4b94f1f1098046a6b1fc59"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "30f3c0c8e7de2eac271968618e2b2233c3319539001bc27d7d21e4f91a99b516"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "30578f768a0a1c430b164b58b8410c3adeb3909d93f1929e1086d74a0e676671"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "8941213dc5f778e74f36207ee4536283e09c1ad388aa1c470029dd6c0bb00eab"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "57f632ac394454991e2c0e063aaca36f20b97904ac2eebee33ddbe6891a0479a"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "cebcd9df3bde5d2c937c3ac2ef7d14da835c744b29120369b9535514530e0035"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "2522a33f6bb034a319a5497d641afae6421855d3bd57071aceff834786aade5d"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "c3fb8696c02ce8015a35c74c0d13627aa485cfcd698e6af4ac275a36e91aa4fb"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
hash = "c7aa2123dc093558b6830e3b126e8fb9237eb8ddaa0d8b6bddd125f4ee3e2999"
metafile = true

[[files]]
file = "mods/doormat.pw.toml"
hash = "6a4bb09a4df14f617a85c2e7d88d19d4dc266cde35866ad55168a22319c371da"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0f08f333a7517cc0750f010f5b61e92c4e18ac8e368465caf8d3f60718c653eb"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "f3409527b8a1065e17e2e86bcf84538957c306c6cb4715cfb1113f85950e68c6"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "adc6a8a7148d69c69a4e4d2b8d443fefd2e1ac8b2486188cc3770a397e1ae41e"
metafile = true

[[files]]
file = "mods/essentialaddons.pw.toml"
hash = "194ee1b847cacdee7687131d8672e96c9865f9ce9ed6024edf883ce408baa32b"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
hash = "145e5425098c6b11a8c3b6dd46631bb99d8b00e18d3be3fd02dcf5d4ddd8bf02"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "fda7d5e527a463ae208d46cc11414f7ee653256c4e120a364c090f3078c2cebb"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "cc4908287780a01a4b8f982712a94330f8368c00728766b5f615470be86db183"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "45e5f322836217ac6ee0ded73e8cd58f675833ba6736093ce836f66a3e34fa3c"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "52b4c90f95ed11567aef8612ce8baec21e9e3a6752d5b3738d3fed5e4470df1a"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1e2c8cc17038e3f8b1abaf0b0ca2b0b72734349c95b37c86ea4b817d29a783f0"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "d80049f4f9438f229920965bfbd1354a23165747a1f84e9b39ab8333bce527c5"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "b0cc562d1f8fe15eb372af25f6ecdc729768ff12a86475165e932f9d480c3aaf"
metafile = true

[[files]]
file = "mods/g4mespeed.pw.toml"
hash = "c5be2d8c61d53f8b8d9ca619120933af3caeeec1b12182219ce53b3eb2d5c62d"
metafile = true

[[files]]
file = "mods/hold-that-chunk.pw.toml"
hash = "bad3336d3cd68a32e63295875d6295a639f363e6c2e93b5708915917af07db6b"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "a38df96fcdc09b74efd86d4e9ae6f1c2609579c769e5270b8af63eb5491417ea"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "7f067e5e50da561ca0ebe73fb1761833f184698752ad9686574d091c7c115afb"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "62def7ce2981026261dfd10797733764788d6a73ef6a3438276ed88f573fc92a"
metafile = true

[[files]]
file = "mods/isometric-renders.pw.toml"
hash = "5df70a5d6bf7b81e964b760fc805ccdc622ffb12cc8aecd15a986607308944c7"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "897b2f34d18a1a78c4b474720ee91e9522e4b0a4c221b97ff255a1a640a2d6ac"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "466283d53e43f1ac000d1bf1509c63ccf4319ea941c8b5f1d271f78053f84ee1"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "5cc41826053a6749eccb6e9f3c69f00f11d8fe91a9e2728f0c2c506eb3590eb7"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "d4676680825fe7899af281d39ee25381af5813bb623e349289216d71ab169db5"
metafile = true

[[files]]
file = "mods/litematica-server-paster.pw.toml"
hash = "16b25fd95b8058993e3303e021870d580aabbf8f6a06ff59bff8a9daca56727b"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "948fbd59bacf979c7d5c513d73172b103597502f01ca26f72e94925ad5a8b8d5"
metafile = true

[[files]]
file = "mods/litemoretica.pw.toml"
hash = "e0862b2d5e420b198ffbd84eef21c67f1fd53bd47a49b7fbea3aeee50daa2abf"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "4f95a4c52f710c15369692d7626592bcb4a9d349888cbcf8054c389bc96b4b98"
metafile = true

[[files]]
file = "mods/magiclib.pw.toml"
hash = "7075df9e43a8cd320d0fe23d95115fede60c7798827d194417fd70ee39a82a7a"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "1794cc7cc6a9de5dbe6f0da45fb6eafbde99472b79ca6faa2424134a659f6e4e"
metafile = true

[[files]]
file = "mods/masa-gadget.pw.toml"
hash = "649780108964b6ac7f2095e84b58ae5bf2b6e47eb8bb0b4ad636245c7189f1ad"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "6a7151fc50bbbd2bdafe990818b8488365c66399b01da85a6549882683fa592c"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "ed2c0eed7870a1c636cc97fe04b74f4c011a6dc89c6763685e23a1e57f52fe25"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "b023a59c1aca83793e37e4e501ad523af2224461f1c1fef888baebfd08d9ec40"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "2e2eecce5dfd3a543e45cf1238df6f48dd35f0334bac5ca520c69690612944c0"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "5bd2f870d084a48c3be2480445ce643c8647b03e0bd2bd529dd7cf56abc3d69b"
metafile = true

[[files]]
file = "mods/nbt-copy.pw.toml"
hash = "2bfd16f61dab9e870e1c46560b323082812aae1cfaa0fdde1673728ad8f8d6ae"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "c5e9af39432436aca1c25a76f4d64ea801acfbfc1a553e714575ffe7dff6ab0c"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "bd50eeda0172d1138f284c2de2d9ffa85fac6f11382447bbb582928c8c3daedc"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "1f5a943f97b3a6ecd6f6ed6a2f724b21e42bc2ab37f3b69e5fed01d8e3860f4c"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "d8a39f9265093d8c9976e8aae8737c87809c448489c3f6e77ccf2fbb501f66f0"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "f7c18ce931e54d5acf87fd59aad5a07d0d076da073126de2dfb53a3698a9a888"
metafile = true

[[files]]
file = "mods/pick-block-pro.pw.toml"
hash = "524499308245964bf57a03b5a89814de458d22c6cb8e24abe87bd4f8b9313a37"
metafile = true

[[files]]
file = "mods/redstone-multimeter.pw.toml"
hash = "f2996ecccbad793ccc17c67d0632c49f8951272b70d4916916196c371065549b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c04f264c67d52adde2b6a10630e89c5ea79c9434fbd30c49629d60f7f66d81ca"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "f7c4ebe89906dd7e771b6a2f760e16766eff8c44d56c17cde02c7472c7be6524"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "d2edbe27c63915de1cf747cc07a6d229cf07a269732b0d3e06704422985347bf"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "a451e712e1d631d26840266ff152f2ba4f7092444d3001c76cff1668a300d7c7"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "51fe4c68e99d25ebbb47ef99a28a8ceeeca038c5e9e24d571d3822f79ef04d50"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "ed94e29df39b49ff95e725cd518ccf1eaec3798382195aea81da3ba7fae4630e"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "090c1ffa1815f260b19353ee892f4d519a489803c88f47bcebb66f5d6409e883"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "1b8abe532d290322f536802ab5e8b428d542ca859dcd39275b8d712cfa4bab7a"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "aba3b1943126909af21653b15fb89331441b47dbcb032c4cf88226d1f0e88a62"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "614e28a7a858b8c21cca1d4bfda9baefa0df220f07795a8901fdc7435299a4b8"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "d81be0be57629b5a37a6bb56f2fe99f95f91269faa22d21e6f79455e77b458a2"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "f2f0c0ae960efa6734bb9b0e731340b73edee33dc7bfe469e49e2707cdd8b8ed"
metafile = true

[[files]]
file = "mods/viabackwards.pw.toml"
hash = "9b04f2984f485fa081ce181944e87dea3015cdfeb6b8813ff68823525d3b553f"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "695d8765874f311d578b9336753d9e4c9c2ce9df927a517614f234237fcd7e7a"
metafile = true

[[files]]
file = "mods/viaversion.pw.toml"
hash = "598193ca1ef75d7afcb0fd24940066b23d2fd93c84b97e5ec125318e764cf13a"
metafile = true

[[files]]
file = "mods/vkm.pw.toml"
hash = "626d1d77923ddaba4c499293e3cf7a521583f72ae0617ea543a493fe809df959"
metafile = true

[[files]]
file = "mods/wecuifix.pw.toml"
hash = "f1845133f1c212416bc8e072d2bda067a62cb6e667acfd146f6ab3be43e73e13"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "f66275b464b4f7b9f08da6a6653f531b261beab9124a3f12e9f00fb93e98709e"
metafile = true

[[files]]
file = "mods/worldedit-hang-fix.pw.toml"
hash = "16c5dc2e8dbf22fbe5d8bdb25566b717201d1e9ea4067d9df957912900201c14"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "dfacf865180969150a6d6d3a4589a42ba99fc1badf6c8b21694bf91376f9b817"
metafile = true

[[files]]
file = "mods/yaca.pw.toml"
hash = "fbb1095928f5194d115829f0cea10068880504f9d1c9e4ec728408bc48041cac"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "0e5d80026ed35fd07d54eac2f973c2711a0da62c2c8b754e01887ec455ea9f16"
metafile = true

[[files]]
file = "resourcepacks/redstone-tweaks.pw.toml"
hash = "a2bbab68ce7c62b5002a2c3c0a10b31190a8b44a39efb6d0eb3870bc65532ca8"
metafile = true
