hash-format = "sha256"

[[files]]
file = "mods/carpet.pw.toml"
hash = "16b4acea5f6398fc5baac567155aff0ee2d8da6b988a446f1c2f3a09f715a64d"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "cd4d0c2db8c45235322fb097de824765c2e9ef1a762f8870b08680b92b8cede0"
metafile = true

[[files]]
file = "mods/wecuifix.pw.toml"
hash = "f1845133f1c212416bc8e072d2bda067a62cb6e667acfd146f6ab3be43e73e13"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "dfacf865180969150a6d6d3a4589a42ba99fc1badf6c8b21694bf91376f9b817"
metafile = true
