name = "RedstoneTools"
author = "Scorpio"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a420e4cf04f9f0b88f8d7aafd87c92b12ada8c461ef0f833499944a39084cdb"

[versions]
fabric = "0.18.4"
minecraft = "1.20.6"
