name = "RedstoneTools"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e76e8049d78d24c8fbb5ade74f5ec1cc9b91673296755a671bd53048607702d2"

[versions]
fabric = "0.18.4"
minecraft = "1.20.6"
