name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2ee582b1204c23b292b02514995a720b0e384e457eaf75310d84c1a0c0f2a25"

[versions]
fabric = "0.18.4"
minecraft = "1.16.5"
