name = "RedstoneTools"
author = "Scorpio"
version = "0.1.3-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c63daaadf824ea006cbaac6f7936617651b6dae044784ee66e8acb367c1c7f47"

[versions]
fabric = "0.18.4"
minecraft = "1.16.5"
