hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "9dd3e283b52dda379cd753d764379458629073f79e710317ec44133fcd8cd22b"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "3eba6a48a871b2f1a77172021fba0bb67e9f1e0da5f765f7a3b02876ed4319e4"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "3ee3c9c0b0ff174a64d522bc10b4dc5544bd413c08e7fb6256b1279d5312d965"
metafile = true

[[files]]
file = "mods/capture-playback.pw.toml"
hash = "051767060b4e355d24e7aec41d791b301676ab55f8030f31c271605ac3972ad0"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "8d2a17465784ab97ad34df034cec5bd3c60bfe907ca21de95787403a0bd420db"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "79155e3ddf3dc7a78b04c13690f10b8ad8a2452acd0cc5b2a7572d45aa1e30f1"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "62425c09a110ae224714d783d0dedf5b8bcf5cc9836b5e351e798ac4fb984fc9"
metafile = true

[[files]]
file = "mods/chunk-debug.pw.toml"
hash = "2adeb31ad0140679873ee02baa6458c924c5e3814a105c1f9e98cac464fb5f43"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "bdd435f7c947798ec87663e9e3e9540c6568ddee128f354a27781ed0656f61e4"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "4f8584269721f9763e1630c9f756648e1ad71613136d58962a2ed4b488a5d5f0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "379c3cfb0a775914a1a66917f710cbfa3baa3e62cade49b5ce9bef55d158a4a6"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8e057387e3d5de45d3c75668cb1508fd4e15b92c376da9bdfe7330f808c4c742"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "8531b91b9d082eeaa0be9c37d60376150bbeaa81bebac6d32fe0f3e58d85e25e"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "1d8e5771bafeb5d6d9d7dbabb46ac32ef7a2123dfdd669b8fc8d8fb27d2fa52a"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
hash = "2e071eefbec9baf820851f77ad44af288d0f152b4aca839cbacbd710e0833717"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "dca5dc49f823416de5f85d76aed968c8f9e8c23a95f63b0b04769f4531ae49ba"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "0eb80e5eab074d997b644663fe4aa11516fc274722d188b843308da8f6474701"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ec6d0bc25af0056fc407f8378a514d3c037561333b51699569e857d71bb24855"
metafile = true

[[files]]
file = "mods/essentialaddons.pw.toml"
hash = "ad0d3b03e19fb6a88672873326a71b1d14754440d603ebf9efbe9507865f449e"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
hash = "2d9895bd2be656543250ec029e41a6061ddedd0ec1bc76fd2c657894bb038d75"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "6b8bdb0032798b056e4850fc662382a58fcec305006db995596306f70fc5f145"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "185acc3828e6bf6b8ccd942347504e0891a43e48d3927c805caccd440fb99f79"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "becab9c4bef60820d4f99eb274635cb151992fe57a6c06e874b3956337108af9"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "07f15bd07ec3c70f2196cb30c0cdcba681eb7afdc6489d0530826593d0dafb87"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "68c3e2aa2cde986b263748a7a1a2582d7de4979e2d91270a593c11884c97fed6"
metafile = true

[[files]]
file = "mods/g4mespeed.pw.toml"
hash = "ca4c6645feef358e09d52c8aaf4fbd6d05480fc8696c44e3d97408aa61be1313"
metafile = true

[[files]]
file = "mods/hold-that-chunk.pw.toml"
hash = "d2f26f68d064d40da83055fe45e330b5740afe1479125ef7c5bb32e61f5324c0"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "bdc937c2e64183c9893325e23188192c1197bb57eba15949161e56df0a9ae124"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "194d69e947b2949051e0d0c15bf1a2e32e30232bdc9140b0f966289a927585b0"
metafile = true

[[files]]
file = "mods/isometric-renders.pw.toml"
hash = "bb57691cb023b059aad4e7054e8b549ebd16a14f94ded79b5ee2de74e1b3806e"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "bf001fb80ada2f6e0158998befd4f34e01f8033d67a2b201e686cbd9c853d374"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "e00302869546019fb2e94ad4a2e81f5b5b7e5c63d5b23ac3f278eaa7b7735437"
metafile = true

[[files]]
file = "mods/joacarpet.pw.toml"
hash = "f0d634be7dc0cc11adf725c0c1fba0ada40f9283deb2de0b13bc7d16ba228661"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "d609573e65a0c0417060648951d396133b295f172fa8f21ce6566d66d27e8320"
metafile = true

[[files]]
file = "mods/litematica-server-paster.pw.toml"
hash = "770303a1d42ca60cbd9b40625c018c975eba9d06e2ca57c4edae8e9757547b57"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "420d672b98615c6e76b08796c38835a9d23527324f71e9d27e72bb2bfe29fb86"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "809e6c0e0db1bed5c31416f55826d30efd48a2e41a3c6a17b3faab3b71c503b3"
metafile = true

[[files]]
file = "mods/magiclib.pw.toml"
hash = "308de68cca7fd2aa1290d48b37756a6a68057a88721c88544ede2184bb47da32"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "b974082e807143052e0df98ad18dacc3c173d034e3a1c66c63e3d750246ef2f1"
metafile = true

[[files]]
file = "mods/masa-gadget.pw.toml"
hash = "990344a8d0b0270f13d30a7045baa734e8d1180112a06c5dcdf2b996a6ca5204"
metafile = true

[[files]]
file = "mods/masaadditions.pw.toml"
hash = "d623c3ed622cc427c748223a9dbda6c730276c19ca040ae92d5463ab1b8001c4"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "7edc8193787bbbea306191ab005d6a9c40c3a44b89a93142ab8d6cd21fc51274"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d99d85da5e60df5e8a0ca1d630da146b858be34206d39cdd00c30053c4e08f5e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "5cf337b85313248799711185282d734c1e525dab914e2ba6edb2d4ea020b906e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "df60e11c24d37f579ce2f3925a91c4c94d191099495d9f5bdc3c8fce0ac93a5a"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "ae90e53681efd54b374f76c267b23865a34a7a08e9343b784403e36140617795"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "2ebef5be65a7fe4de38ae9cc4c3f9f666ec759509623ba1d7cc1f3741fde2a83"
metafile = true

[[files]]
file = "mods/nbt-copy.pw.toml"
hash = "04cbef7e357aa7e104e9cc9b5b158244b88a7dd224ca65a6f526cbc2807a7d66"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "7de68ea41d7e6ee9041299bd649001d3aa042df0e6cac0502f24c7a5ec3fcbe3"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "fc10ab4fd98244dc1512adbfdb47bdc11fe43c860996cd4067834233fce9a562"
metafile = true

[[files]]
file = "mods/pick-block-pro.pw.toml"
hash = "14e36ed0e0181ef071a781ccd4900f329726e9b70cd4af1607f763da2110dcb5"
metafile = true

[[files]]
file = "mods/redstone-multimeter.pw.toml"
hash = "41eb68f068b3a4c5e8231268eaf57e8174767cdcbadfbe7fb188808c5e7e0453"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "46205f112b6af894a1d88e9e2fc33c360019c6d6513ac659aa78866ea8ec348a"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "63d238e47791f12553944c44dc2c0be0705b4b0625ef41f344bae01027543ce2"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "c6e4a9c612e7dd473f07132f041c14ce0ef5c7800308f11f703a48fb9c15664b"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0c83c344046d0b96fd7dcd9e5c98c44caa3d307126d502f202dba50855304fb9"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "bee56d1f3c757a0dc573520291147c3b0ba31a11963ad620a493dea36fcb3d5b"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "2ddb145275ccfb4425411eb127a84e6c4de03b279e1db8fc79b006755aa65bce"
metafile = true

[[files]]
file = "mods/subtick.pw.toml"
hash = "7b8d2454dbf99c87555626991697597b931ceed28f4a4430f1d5c4a8fe97d24f"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "ab3020452d219a7a54299e7cc20e582496b021284d55f45facb09274da7be931"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "c9b237d4c74940c6a5c903a75184226c395650c2c9763702588ac7d8edb61d14"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "a991f3c5c1001e4eb4d2d576167f4818fa5d35458960f4f899a215c187a40d46"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "dc3661e5de6d3650a6787d596d57a2e96d9a701d606438a988fcf4ed4387d5c4"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "e030656570132a7e3b09d63b52a4479de910e05c787a3d8309d2bde493ffb3f7"
metafile = true

[[files]]
file = "mods/viabackwards.pw.toml"
hash = "9b04f2984f485fa081ce181944e87dea3015cdfeb6b8813ff68823525d3b553f"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "695d8765874f311d578b9336753d9e4c9c2ce9df927a517614f234237fcd7e7a"
metafile = true

[[files]]
file = "mods/viaversion.pw.toml"
hash = "598193ca1ef75d7afcb0fd24940066b23d2fd93c84b97e5ec125318e764cf13a"
metafile = true

[[files]]
file = "mods/vkm.pw.toml"
hash = "30010799d341a8079d6d69bc43afac5f3e6299efc875c5109e996be3fd492df6"
metafile = true

[[files]]
file = "mods/worldedit-hang-fix.pw.toml"
hash = "16c5dc2e8dbf22fbe5d8bdb25566b717201d1e9ea4067d9df957912900201c14"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "fd9d3a7e8347da0be1cbb961cb52a865b294013bc001edae762260fae1ddb099"
metafile = true

[[files]]
file = "mods/worldeditcui-fabric.pw.toml"
hash = "7b46502f835cc6fbef7bb19c6f99a64f943631baf3463dd15da7e66dc340acb0"
metafile = true
