name = "RedstoneTools"
author = "Scorpio"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bfa5bcdc6caae67bbc6e5aa771b1681482dfb96ef8236ebf5394734da5f7120"

[versions]
fabric = "0.18.4"
minecraft = "1.18.2"
