hash-format = "sha256"

[[files]]
file = "mods/auth-me.pw.toml"
hash = "91476bba79c18463c774a2d7342ee686910628e6c7a43d4097ecc14ffeb0c0fa"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b138c7b832b037f83d62d6a8ef0d06da8394812bd8f5f554f888cb901d11c4cc"
metafile = true

[[files]]
file = "mods/better-suggestions.pw.toml"
hash = "86e990df7686c4b0c6fa307e03126edf45e607a945097dbba95d175742a0d395"
metafile = true

[[files]]
file = "mods/capture-playback.pw.toml"
hash = "f0e5fe39190965dbbf7cc31cd168a5254a899d34a9038b585d9442863b22929c"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "b37caad4b6f209c6a348892f23f75265e3e752f4b2918799fc1fe395c101fd58"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "7b023eec6ada4f3dd7ca9a6b9e6a5a9fe1be99142bbdf3d5db205c9e4ed96227"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "bd7602c12a25e231fdc9861fe9695ed5f5a6ba691f6c425f140af2a33dc1c287"
metafile = true

[[files]]
file = "mods/chunk-debug.pw.toml"
hash = "579bb1a074be9b637b4e79b75a4bb39e8c4ca375c0072b505d2efd9555b50524"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "1989379303c9fd7dd5a861583da08e7221d72e7dfb777633e9c51213abc5816b"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "d5559297809fa72fd0255dcea3700705c2e317c1c9f702dcef0017a1b7f2e225"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "79aaa3977274f2dfe851592d25237abc98fa889a3b9c0d1ccbc1de295e115b26"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "57f60ccfa00d021ffe2ac77837fb396aac9bf1fd3ebf161de9ad25dfd368b633"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "de26cd1f8d8e16df0bb8681cae36bc02fba5c4f7f4f854928a6102300cc321b3"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "8f91225a9b235e6357a40082c5137d0cd8d97f925146255df5cbcd76614a1866"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
hash = "729be1a6283fe91bf867944a24966cf5d0e2de3ef5fca52decc4a18cf2fe37f4"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "debec99fa8997b52bcacb87a0b810c8f1c8b881c2facdd5190200ab118128b4e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "1c0c020a499f58d36d68a46ce8354d4ad83692466f4cb5b0602d4a5a9d2cc9f5"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "1e9b90518323ea9d31158b7cf4c44a8658750981aadf2fed216ecbf128960a0c"
metafile = true

[[files]]
file = "mods/essentialaddons.pw.toml"
hash = "25677016b173d0a0d99c50bc0acb1f0d69bb3f07e7290793a042e636edbd2f2b"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
hash = "67d3939b6a70505ccee2e5c18704eaafafaf63491b1eb49718ef250f05bc0d3f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "b01b73b7e30086bd19fb8c290ecd54fe3048432d4a17db21434bb8ef70eced7b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "11e628eff2e3368e735b4efe21ed3782479ba8702495d340fc4dd78c91e06e30"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "f33c2ef8f68a8d94bd229fa4b7e168cfb1a234697ca047befdf2da5ca4d65009"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "637fb63d9c6dd7f66f9a734f74f87fba9a0e1a43f9cb4bcf5241bf19fe0487de"
metafile = true

[[files]]
file = "mods/g4mespeed.pw.toml"
hash = "6f5b76353d33a15511a6fb39c22cb49de2235bb8c66c6e864c11fdbc9999269a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2e704e5192aaeafcfad96da3bca1ed35268f3b09beb9f91f398530a2596ee16d"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "6e9c6908c7df5fa0ade025290cf50f589b94efa6839bb8303b9f41ed7f50e82d"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "3526659567d9d79e3dabb607279a2af40318e2598dfa9de0af9fbadd146a7be0"
metafile = true

[[files]]
file = "mods/isometric-renders.pw.toml"
hash = "b03892b94acb200cd78a3e19f04a6511f7bdac1345a766d62db8ac93e38f9cd6"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "4c5a106d6eb262b6b554a7a4532735293b60b3d49cd5f5d62a8327aae95768b1"
metafile = true

[[files]]
file = "mods/joacarpet.pw.toml"
hash = "9a532e1d4fbdaf7bb8a443001a6cea770b21124a191ada8d282373a8a241ca65"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9dd2808f043c1fb8dfcf699174790d6f082b6d56aff1fe4573927d8a722931bb"
metafile = true

[[files]]
file = "mods/litematica-server-paster.pw.toml"
hash = "0aa5c4dc006f7b6dfc9b97a7bb7a6f5651047bf6af7975843a2966f84cab57d1"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "1b18d8466a8bc7927846bce45dd4383178a9c71a7461260957ed0056e82df9e9"
metafile = true

[[files]]
file = "mods/litemoretica.pw.toml"
hash = "e53f3d257ea05baac1005608be0a2e4db68cf193c8e9344ea1b8389aa9dcbd92"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "78abf7fccb5086b0a7353916b8e61cf52333743425f3f1f925ff5764881114fa"
metafile = true

[[files]]
file = "mods/magiclib.pw.toml"
hash = "fe70bdd830eaa19b8ca2a35ee4472479539fe49c35150fc8b2375c0b5abf56a3"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d77892679408ebbf739ed7dbea75d740a54dec106bffae1f1a5f35158429e34a"
metafile = true

[[files]]
file = "mods/masa-gadget.pw.toml"
hash = "66a6fcce033a1914eb09a82720299b90443c790402067ea3a680d11afe38cb3f"
metafile = true

[[files]]
file = "mods/masaadditions.pw.toml"
hash = "41e05e61203621c45fe1af11a5e38330efb4a2998895581fd42796e12bbcfaf9"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "dc7a8014329d06fac1fdaa31997f280e9028d5ba9f9a28fef43aba91757740d2"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a63b58c7f98368327c83a77b58f8185322941ab0b722d06a21cbd68ce921818c"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "1517a373ff7b6c90391ccb5d12b4013bf01bee2640bb1f03125f42c2ccbce3cd"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "46a0664543eb34cc569ee5312e24e2c8c73e20ad3471bcefb5634457bb87ca52"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "9b41e704382074e5576950cf87afef72d2610441c61cd522ab56a1a2cb7de88d"
metafile = true

[[files]]
file = "mods/nbt-copy.pw.toml"
hash = "7a436f1e57436719f8181e010bd8cc7565472661fb49aaeb2ea7f5f0d88b052c"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "4caf4c3da827e2711f5e7fc7a9c3ee56f48df1dd8408d88ef5579792c8b3219a"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "2c9a3a19219be7dc4fc3d1dca3346b93cb931743dc2ddd6ae49f7995bd2bf00f"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "fc10ab4fd98244dc1512adbfdb47bdc11fe43c860996cd4067834233fce9a562"
metafile = true

[[files]]
file = "mods/pick-block-pro.pw.toml"
hash = "553b2932f40f8444b92eb1d5e4e71171b8aa0a56248b7fe421188c484ba1e085"
metafile = true

[[files]]
file = "mods/redstone-multimeter.pw.toml"
hash = "60871c83fc12f20babdd82b11d122cbdbb8901cd437a76edb8b46ccf57fcc2d9"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c7a36cf5965c7c3b32a816f250d43f440a4e95c64e856bf47cca79b9f916660d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "11730f00e462b590af8efac554bc8bd508f7a026e66ad27475b008aeaed870ad"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c0d2a8f6068419557b957615e7db354a0e0caa994b18c98563307a9feb8a0b5f"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "9e40605536180152b87270aadf758d93b39f2da39e95534d163fa501c5131af6"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "46a3ac265c2073f5f844a1fbcc1822c2ed897bc6415ba536bf57208c89d5a31a"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "c9b237d4c74940c6a5c903a75184226c395650c2c9763702588ac7d8edb61d14"
metafile = true

[[files]]
file = "mods/techutils.pw.toml"
hash = "cc34d5fd07de0a8913d94eaa727e3fdd48c97dbcbae69fab84301b9ae9f5199e"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "339f5e4f18c59e538a36e3bf30c2d28b95500efdf4ca0b63c989178c35f8bfdb"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "1f9f1ad2d706db90061bb2f9fdb4d3244643bb714e3376d1cfb90fc435848a7e"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "1b1da6f11d2a97ed47e926810d2294d6747fb2a03695e1e5338e1206d1cc0a19"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "28649cb6eb3d04f7b7dbb83feaaca46ada5190c4b3f72d3b35af314c64940611"
metafile = true

[[files]]
file = "mods/vkm.pw.toml"
hash = "7285cce47f117280d2adf46404cbf44f2bee0d93706ced91945b560d02c02307"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f5e867e1ec8b1cfc0453a690c53be70948c261b3b6d0c90743a22ba0ef1fa748"
metafile = true
