hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1155ba93a663467c095918389823c5ff60ab693a82b15c86fcde791fdb58f541"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "f741ac02824811b5066a2d65fa3eb779381182ebe8921f35898705b715026dba"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "26532c993ff5a93409f6d8af7bdaf81b4569fa698bdc18b75cfd55ac6b7a46f4"
metafile = true

[[files]]
file = "mods/better-suggestions.pw.toml"
hash = "07279fb13f8e56dc5c34599135db5cbda3f7c272da527b2d8c8a72efcbfb7bbe"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "26225ec0a868b5bba3e3c1e164b715c67f122b6f7f5471fb5d0ba7a01e604d27"
metafile = true

[[files]]
file = "mods/capture-playback.pw.toml"
hash = "80e37f1618bcaff33b1bcb14a8b9dd370c965e6aa7f7808a2668eed1b5c35a80"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "cdd6ac74631a1065fcd17d4730211469b697a6dc42470f19c84025a41446e749"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "5232e0ee099fe22654997c772787c7c4907c5c8fe1797f81cb94ee3d245cca05"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "89efbe61f49af69ab78cf6ad28204b1dc4f50759a6187c3e8b6859f741b82723"
metafile = true

[[files]]
file = "mods/chunk-debug.pw.toml"
hash = "d84f610c0610a63c73d9dc59496b5d026b733f26a8ffba04db20c5a23db84801"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "dbc0500ac9b018276a75ff994c1b24716183f31345d6a06adfa052f7ac88d86d"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "cb921fe890021488531d48f77c52d3f6f71f51b91bc40d41c5e9badd7fc5b9c1"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "4f5155a0147e94e03d788b0f090e4bcf3772d0bfccc1cd98f6480b25e9610893"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "788981734d10b728c2fb728268b6e63070c076a3ffedae19498c20a7ae6f1bdb"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "5a980b9299e202f0120b21ad4f7ff62647cdfa7916b5d0b4c1d2f770c6b9da2a"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "62b020c4da3425d223728244d92b644f5c33e3afad891aee2bfc84e86e221561"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "527298a4a5022425b526aa736b8207616ad1a94151b538866edbc1a76a701e1a"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
hash = "729be1a6283fe91bf867944a24966cf5d0e2de3ef5fca52decc4a18cf2fe37f4"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "debec99fa8997b52bcacb87a0b810c8f1c8b881c2facdd5190200ab118128b4e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c8cc6fbf109918c5334ddc24ad9db7c4ace27e8ae588b2a4186324ad42dec9c9"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "e61083893ec8e71bb5fe9ccf0364895ae856a23f7c6731ced01e7195dc545b2c"
metafile = true

[[files]]
file = "mods/essentialaddons.pw.toml"
hash = "359bb6baf52cb567c13917a9b0746162e79161719b12711991ce59c575693d9e"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
hash = "25722dfc2808bc273f94568aaa010ef971b6c50257e912147a28a47f0ef63e94"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "4777616c9ac06bb81ea0810daea10c11fbc81a515eb4eb2ba2777b549fc7bced"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "11e628eff2e3368e735b4efe21ed3782479ba8702495d340fc4dd78c91e06e30"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "f33c2ef8f68a8d94bd229fa4b7e168cfb1a234697ca047befdf2da5ca4d65009"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "dcdb57d3f6b4c39accbf01dea794c154c2be7913c53d1ac7722d919cb62e7429"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "420336660db303c9c1fc79eb8da00ae983fdf8dbe2d685fd7e1ab74be08d08a9"
metafile = true

[[files]]
file = "mods/g4mespeed.pw.toml"
hash = "89af9c835a6cf65d3e4474cb4136aad4dcdea012480fca04829dc03e44117a6d"
metafile = true

[[files]]
file = "mods/hold-that-chunk.pw.toml"
hash = "7ef9c53b1aef83f742cbe52a7a5e0419c37834a685d2b73ebe0963a98896b4fc"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "0ee1a55a949cd7b6ac15f41b00589541f3fcc0f85dda1df4e2d2c3dc36fc2d0f"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "294857ae03a401907814df409641e1de3c2d3c915063a29a17523d28fdeb0fe1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "3526659567d9d79e3dabb607279a2af40318e2598dfa9de0af9fbadd146a7be0"
metafile = true

[[files]]
file = "mods/isometric-renders.pw.toml"
hash = "90d2a2e322863c819eb94431a3eb32dcef5dcb0502705b31c754d775d22e26e3"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "3d76e5f6f30066c5dc1e5cedc1a1c98eabcaff1d7e6d117090ef862aa3365bfd"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "80ec00b5476e49841bcca252ace725d47b3c30e36d4308267ec594e3428d958e"
metafile = true

[[files]]
file = "mods/joacarpet.pw.toml"
hash = "b84505ffe3cf65d18c991f052a837b6aa009c7818283f452b09180c4561c7681"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "f5543ccdf093355cca8409d7d0feb0301f4b5e83f4d35a8f4c3f9b4c28ef1764"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "6bd8f9e0d4378e300c41dc52a93c14c1ac735770781ef8a5f1aaf46b4cfef6da"
metafile = true

[[files]]
file = "mods/litematica-server-paster.pw.toml"
hash = "9a57e937ad2e49664bc35dc14cebaf7fa46d98873d993a6ba308d0b7d949e26f"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "40f19104f891e4f66d44bc464234297f299e9e2ac0a31f17d032df9431caca09"
metafile = true

[[files]]
file = "mods/litemoretica.pw.toml"
hash = "4d682629f2b4f0550aaa62d943814dcc7e7dfe355becb0dce0f81336150467a5"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "bd43a13951de504be4138561460784d107c303416b3f2f405fbc810ecb5c946e"
metafile = true

[[files]]
file = "mods/magiclib.pw.toml"
hash = "45db636582a62a44b7f829cbe92665ce58b792b234c5379c41382fd3946607d3"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "df2f9832025a1ea8967d17d8a9aa4d7c43a87698ffb9aa4b93d3fa218b190b49"
metafile = true

[[files]]
file = "mods/masa-gadget.pw.toml"
hash = "69e48278d5145fd1be6747a511dfb8fcd86dfe760f66da08de205a8712e4cadc"
metafile = true

[[files]]
file = "mods/masaadditions.pw.toml"
hash = "041f0be89a7cbc4738cbd583799f2f5a46218144c79d7de6f1cabc0c7c14115a"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "20025fcabf5047776cbd62fa8ad2467f11bd29477a98598a897824a18ca2e279"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "086e0bb300614b1fd22106dc978e6e9bef6690bc8a6479e675489c8a54d8e42b"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "911e46bb08693249ce6106951cf42d60e99e5de9f67bd26b30c0bfea4a8348d6"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "789352db33bd7287e45e1fd16182f786ac07f068aedcd32a57372f79a3cd4973"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "8680c85b3fedeec64e3e8a499cab72d73423f6175642cd3b8cb0f87cca7c1138"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "c6d68f578459c16869f46aeb9271cf48f0c9f43cd62d8663348cb804f921eaf0"
metafile = true

[[files]]
file = "mods/nbt-copy.pw.toml"
hash = "2bfd16f61dab9e870e1c46560b323082812aae1cfaa0fdde1673728ad8f8d6ae"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "4caf4c3da827e2711f5e7fc7a9c3ee56f48df1dd8408d88ef5579792c8b3219a"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "587bf591cc3b814e6f18e26b9f9a5f19793a660ff883441bc82a8c69b86a5ec7"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "c19dd9098f0193511ce19b0c7f988a8f001c5b1491eea81a1eaebbbbfee23dd9"
metafile = true

[[files]]
file = "mods/pick-block-pro.pw.toml"
hash = "5e2befb8066c921ed9941a5d8a6cb12d0a3dbbf19648ade577c31f17bc7330fe"
metafile = true

[[files]]
file = "mods/redstone-multimeter.pw.toml"
hash = "4f79e4b7b3994c919935d8f60bdc10164e62c2c9db4cf6541e56f368bfcee71d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "3cf284a40a3622e9c5709c62c58b62c7ee0fbad1fac21322afa7fc4663a866fb"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "10328073c24d9cc4dec408fd3b89ac00d9d28860cf315a6b1167fb8e9549be24"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "41de20f227babbe1707422b7a3f88ebcd2f45b9e02a32d0a3785bec009a1a329"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "303f6c9eae9e001b4119ee78fafc5388e3a5f643d2eb7a73af84ad4223fe12d6"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c0a205102a2f7a34054bea6b94f2c4793ff21b2aa758a0f1e08773f79b0b80cd"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "f89e29023606d8d37d1e3c216e30e8578e3860f8beae6c9d6e0a3c17c7d3b95e"
metafile = true

[[files]]
file = "mods/subtick.pw.toml"
hash = "da40225ebbe83e33ba5600a48f21063b10cd4d9788c2a7ee81f8ad10f24371b0"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "f27517a96d83aceaabb78c2a656a3e35ebc30ca15fbd7e72ae6858f881ff37df"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "559f2ea31f28d52fec50811c21dd354fd71c6721bc7942eec38436037311b7b8"
metafile = true

[[files]]
file = "mods/techutils.pw.toml"
hash = "fb8b3ef7197b9195d00f54aa3a5545078f13822b5819a5f166c8e2516cb3e081"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "83c620442bea06d289f1e63f280921c3f3eaf6f01bf553dd8e1a897e74227ed8"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "129d5a200ee5c6d20e60acf5cd3cbbb254cf2a06be205b6bd759aefdc7fb5189"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "f72c3d281ddfc0fdc3a53aef418087f6a8bce6fb5634a13d19a907061c4ea6d4"
metafile = true

[[files]]
file = "mods/viabackwards.pw.toml"
hash = "9b04f2984f485fa081ce181944e87dea3015cdfeb6b8813ff68823525d3b553f"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "695d8765874f311d578b9336753d9e4c9c2ce9df927a517614f234237fcd7e7a"
metafile = true

[[files]]
file = "mods/viaversion.pw.toml"
hash = "598193ca1ef75d7afcb0fd24940066b23d2fd93c84b97e5ec125318e764cf13a"
metafile = true

[[files]]
file = "mods/vkm.pw.toml"
hash = "ea0a613140d6887bcd3366e588b9eca29868e6b8d89885a56e10ceb1c93c7d53"
metafile = true

[[files]]
file = "mods/worldedit-hang-fix.pw.toml"
hash = "16c5dc2e8dbf22fbe5d8bdb25566b717201d1e9ea4067d9df957912900201c14"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "078433b48ef61031dc4b63673f8ace0461e193a0bd5d5f9890f8fa1f8d24c986"
metafile = true

[[files]]
file = "mods/worldeditcui-fabric.pw.toml"
hash = "6667c0d15bd2e44970aee2fb2ebe1dc81b53cb4bde6a51e8142e8c6591a894e2"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f2c2f24f6eb93eed3e6be7ff84fafe01fa08f0cc5c22e26b90b5f374e6b3c0b5"
metafile = true
