name = "RedstoneTools"
author = "Scorpio"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "689dea2c3ecf393b5246a38cfc119de3d450d45f08a693de0b0f81d3da9d27a4"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"
