name = "RedstoneTools"
author = "Scorpio"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ce8baa034dcfe1ca1a6f58ceecce9246170ec9fc6fa3e2797fbc6e36cfacb59"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"
