name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "960658343343895292a8cf013a93572b48ae0ca089800ad55ee16e6005f8a1b5"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"
