name = "RedstoneTools"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5511c150ff12c264b68c610c9a47320262975214ba2bae282c6046c475b62448"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"
